shopproject/shop/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

urlpatterns = [

   path('', main_page, name='main_page'),
   path('catalog/', catalog_page, name='catalog'),
   path('contacts/', conatcts_page, name='contacts'),
   path('how_to_find/', how_to_find, name='how_to_find'),
   path('categories/', categories, name='categories'),
   #path('cartuser/', cart, name='cart'),
   path('cabinet/', cabinet, name='cab'),
   path("categories/<int:id>/", category_detail, name='category_detail'),

   path('admindashboard/', adminpanel, name='adm'),

   path('guitar/', GuitarListView.as_view(), name='guitar_list_view'),
   path('guitar/<int:pk>/', GuitarDetailView.as_view(), name='guitar_detail_view'),
   path('guitar/create/', GuitarCreateView.as_view(), name='guitar_create_view'),
   path('guitar/<int:pk>/update/', GuitarUpdateView.as_view(), name='guitar_update_view'),
   path('guitar/<int:pk>/delete/', GuitarDeleteView.as_view(), name='guitar_delete_view'),

   path('category/', CategoryListView.as_view(), name='category_list_view'),
   path('category/<int:pk>/', CategoryDetailView.as_view(), name='category_detail_view'),
   path('category/create/', CategoryCreateView.as_view(), name='category_create_view'),
   path('category/<int:pk>/update/', CategoryUpdateView.as_view(), name='category_update_view'),
   path('category/<int:pk>/delete/', CategoryDeleteView.as_view(), name='category_delete_view'),

   path('guitarform/', GuitarFormListView.as_view(), name='guitarform_list_view'),
   path('guitarform/<int:pk>/', GuitarFormDetailView.as_view(), name='guitarform_detail_view'),
   path('guitarform/create/', GuitarFormCreateView.as_view(), name='guitarform_create_view'),
   path('guitarform/<int:pk>/update/',GuitarFormUpdateView.as_view(), name='guitarform_update_view'),
   path('guitarform/<int:pk>/delete/', GuitarFormDeleteView.as_view(), name='guitarform_delete_view'),

   path('cart/', CartListView.as_view(), name='cart_list_view'),
   path('cart/<int:pk>/', CartDetailView.as_view(), name='cart_detail_view'),
   path('cart/create/', CartCreateView.as_view(), name='cart_create_view'),
   path('cart/<int:pk>/update/', CartUpdateView.as_view(), name='cart_update_view'),
   path('cart/<int:pk>/delete/', CartDeleteView.as_view(), name='cart_delete_view'),

   path('order/', OrderListView.as_view(), name='order_list_view'),
   path('order/<int:pk>/', OrderDetailView.as_view(), name='order_detail_view'),
   path('order/create/', OrderCreateView.as_view(), name='order_create_view'),
   path('order/<int:pk>/update/', OrderUpdateView.as_view(), name='order_update_view'),
   path('order/<int:pk>/delete/', OrderDeleteView.as_view(), name='order_delete_view'),

   path('status/', StatusListView.as_view(), name='status_list_view'),
   path('status/<int:pk>/', StatusDetailView.as_view(), name='status_detail_view'),
   path('status/create/', StatusCreateView.as_view(), name='status_create_view'),
   path('status/<int:pk>/update/', StatusUpdateView.as_view(), name='status_update_view'),
   path('status/<int:pk>/delete/', StatusDeleteView.as_view(), name='status_delete_view'),

   path('cartitem/', CartItemListView.as_view(), name='cartitem_list_view'),
   path('cartitem/<int:pk>/', CartItemDetailView.as_view(), name='cartitem_detail_view'),
   path('cartitem/create/', CartItemCreateView.as_view(), name='cartitem_create_view'),
   path('cartitem/<int:pk>/update/', CartItemUpdateView.as_view(), name='cartitem_update_view'),
   path('cartitem/<int:pk>/delete/', CartItemDeleteView.as_view(), name='cartitem_delete_view'),

   path('orderitem/', OrderItemListView.as_view(), name='orderitem_list_view'),
   path('orderitem/<int:pk>/', OrderItemDetailView.as_view(), name='orderitem_detail_view'),
   path('orderitem/create/', OrderItemCreateView.as_view(), name='orderitem_create_view'),
   path('orderitem/<int:pk>/update/', OrderItemUpdateView.as_view(), name='orderitem_update_view'),
   path('orderitem/<int:pk>/delete/', OrderItemDeleteView.as_view(), name='orderitem_delete_view'),


   path('choose_guitar/<int:pk>/', GuitarOnClickDetailView.as_view(), name='guitar_onclick_detail_view'),

   path('login/', login_user, name='login_user'),
   path('registration/', registration_user, name='registration_user'),
   path('logout/', logout_user, name='logout_user'),



]  

shopproject/shopproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.contrib import admin
from django.urls import path, include

from .settings import DEBUG, MEDIA_URL, MEDIA_ROOT

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('basket/', include('cartapp.urls')),
    path('api/', include('apishka.urls')),
]

if DEBUG:
    urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

shopproject/shop/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator


MAX_LENGTH = 255

class GuitarForm(models.Model):
    name = models.CharField(max_length=MAX_LENGTH, verbose_name='Название формы гитары', unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Форма гитары'
        verbose_name_plural = 'Формы гитар'

class Category(models.Model):
    name = models.CharField(max_length=MAX_LENGTH, verbose_name='Название категории гитар', unique=True)
    photo = models.ImageField(upload_to='photos', verbose_name='Фотография')
    description = models.TextField(null=True, blank=True, verbose_name='Описание категории')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категория гитары'
        verbose_name_plural = 'Категории гитар'

class Guitar(models.Model):
    name = models.CharField(max_length=MAX_LENGTH, verbose_name='Название гитары', unique=True)
    description = models.TextField(verbose_name='Описание')
    price = models.FloatField(verbose_name='Цена', validators=[MinValueValidator(0.0)])
    photo = models.ImageField(upload_to='photos', verbose_name='Фотография')
    in_shop_quantity = models.PositiveIntegerField(default=0, verbose_name='Количество на складе')
    guitar_form = models.ForeignKey(GuitarForm, on_delete=models.PROTECT, verbose_name='Форма гитары')
    category = models.ForeignKey(Category, on_delete=models.PROTECT, verbose_name='Категория')
    is_exists = models.BooleanField(default=True, verbose_name='Доступность к заказу')

    def __str__(self):
        return f"{self.name} - ({self.price} рублей.)"

    class Meta:
        verbose_name = 'Гитара'
        verbose_name_plural = 'Гитары'

class Cart(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='Пользователь', unique=True)

    def __str__(self):
        return f"Корзина пользователя {self.user.username}"

    class Meta:
        verbose_name = 'Корзина'
        verbose_name_plural = 'Корзины'

class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, verbose_name='Корзина')
    guitar = models.ForeignKey(Guitar, on_delete=models.CASCADE, verbose_name='Гитара')
    quantity = models.PositiveIntegerField(default=1, verbose_name='Количество')

    def __str__(self):
        return f"{self.guitar.name} x {self.quantity} в корзине"

    class Meta:
        verbose_name = 'Позиция в корзине'
        verbose_name_plural = 'Позиции в корзине'
        unique_together = ('cart', 'guitar')

class OrderStatus(models.Model):
    name = models.CharField(max_length=MAX_LENGTH, verbose_name='Название статуса', unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Статус заказа'
        verbose_name_plural = 'Статусы заказов'

class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Пользователь')
    status = models.ForeignKey(OrderStatus, on_delete=models.PROTECT, verbose_name='Статус')
    create_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    address = models.TextField(verbose_name="Адрес доставки")
    comment = models.TextField(max_length=MAX_LENGTH, null=True, blank=True, verbose_name="Комментарий к заказу")
    total_price = models.FloatField(default=0.0, verbose_name='Общая сумма', validators=[MinValueValidator(0.0)])
    
    first_name = models.CharField(max_length=100, verbose_name='Имя покупателя')
    last_name = models.CharField(max_length=100, verbose_name='Фамилия покупателя')
    middle_name = models.CharField(max_length=100, null=True, blank=True, verbose_name='Отчество покупателя')
    end_date = models.DateTimeField(null=True, blank=True, verbose_name='Дата окончания заказа')

    def __str__(self):
        return f"Заказ {self.id} от {self.user.username}"

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, verbose_name='Заказ')
    guitar = models.ForeignKey(Guitar, on_delete=models.PROTECT, verbose_name='Гитара')
    quantity = models.PositiveIntegerField(default=1, verbose_name='Количество')
    price = models.FloatField(verbose_name='Цена на момент заказа', validators=[MinValueValidator(0.0)])

    def __str__(self):
        return f"{self.guitar.name} x {self.quantity} в заказе {self.order.id}"

    class Meta:
        verbose_name = 'Позиция в заказе'
        verbose_name_plural = 'Позиции в заказах'
        unique_together = ('order', 'guitar')

shopproject/shop/forms.py
from django import forms
from .models import Guitar, GuitarForm, Order, OrderItem, OrderStatus, Cart, CartItem, Category
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class GuitarModelForm(forms.ModelForm):
    class Meta:
        model = Guitar
        fields = ['name', 'description', 'price', 'photo', 'in_shop_quantity', 'is_exists', 'category', 'guitar_form']

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name', 'photo', 'description']

class GuitarFormForm(forms.ModelForm):
    class Meta:
        model = GuitarForm
        fields = ['name']


class Order(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['address', 'total_price', 'user', 'status', 'first_name', 'last_name', 'middle_name', 'end_date']


class CartForm(forms.ModelForm):
    class Meta:
        model = Cart
        fields = ['user']

class OrderStatusForm(forms.ModelForm):
    class Meta:
        model = OrderStatus
        fields = ['name']
        widgets = {'name' : forms.TextInput(attrs={'class': 'form-control'})}

class CartItemForm(forms.ModelForm):
    class Meta:
        model = CartItem
        fields = ['quantity', 'cart', 'guitar']

class OrderitemForm(forms.ModelForm):
    class Meta:
        model = OrderItem
        fields = ['quantity', 'price', 'guitar', 'order']
      

#для авторизации и регистрации

class RegistrationForm(UserCreationForm):
    username = forms.CharField(
        label='Логин пользователя',
        widget=forms.TextInput(attrs={'class': 'form-control dark-input'}),
        min_length=2
    )
    email = forms.CharField(
        label='Электронная почта',
        widget=forms.EmailInput(attrs={'class': 'form-control dark-input'}),
    )
    password1 = forms.CharField(
        label='Придумайте пароль',
        widget=forms.PasswordInput(attrs={'class': 'form-control dark-input'}),
    )
    password2 = forms.CharField(
        label='Повторите пароль',
        widget=forms.PasswordInput(attrs={'class': 'form-control dark-input'}),
    )
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class LoginForm(AuthenticationForm):
    username = forms.CharField(
        label='Логин пользователя',
        widget=forms.TextInput(attrs={'class': 'form-control dark-input'}),
    )
    password = forms.CharField(
        label='Введите пароль',
        widget=forms.PasswordInput(attrs={'class': 'form-control dark-input'}),
    )

shopproject/shop/templates/order/order_confirm_delete.html
{% extends 'base.html' %}
{% load static %}

{% block title_name %}Guiznotes - Удалить заказ{% endblock %}

{% block link_style %}
    {{ block.super }}
{% endblock %}

{% block content %}
{% if user.is_authenticated and user.is_staff %}
        <div class="container contact-container">
            <div class="row justify-content-center">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <h2>Удалить заказ №{{ order.pk }}?</h2>
                            <form method="post">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-custom">Удалить</button>
                            </form>
                            <a href="{% url 'order_list_view' %}" class="btn btn-custom mt-3">Вернуться к списку заказов</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
{% else %}
            <br>
            <h1 class="text-center">Сначала войдите в аккаунт администратора</h1>
   {% endif %}

{% endblock %}

shopproject/shop/templates/order/order_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title_name %}Guiznotes - Заказ №{{ order.pk }}{% endblock %}

{% block link_style %}
    {{ block.super }} 
{% endblock %}

{% block content %}
   <div class="container contact-container">
            <div class="row justify-content-center">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <h2>Заказ №{{ order.pk }}</h2>
                            <p>Дата создания заказа: {{ order.create_date }}</p>
                            <p>Адрес: {{ order.address }}</p>
                            <p>Комментарий к заказу: {% if order.comment %}{{ order.comment }}{% else %}Нет комментария к заказу{% endif %}</p>
                            <p>Итоговая сумма заказа: {{ order.total_price }} рублей</p>
                            <p>Статус заказа: {{ order.status }}</p>
                            <p>Никнейм покупателя: {{ order.user }}</p>
                            <p>Имя покупателя: {{ order.first_name }}</p>
                            <p>Фамилия покупателя: {{ order.last_name}}</p>
                            <p>Отчество покупателя: {% if order.middle_name %}{{ order.middle_name }}{% else %}Нет отчества{% endif %}</p>
                            <p>Дата завершения заказа: {% if order.end_date %}{{ order.end_date }}{% else %}Заказ ещё не завершён{% endif %}</p>
                            <h3>Содержимое заказа:</h3>
                            <ul>
                                {% for item in order.orderitem_set.all %}
                                    <li>
                                        <strong>Гитара:</strong> {{ item.guitar.name }}
                                        <br>
                                        <strong>Количество:</strong> {{ item.quantity }}
                                        <br>
                                        <strong>Цена за штуку:</strong> {{ item.price }} рублей
                                        <br>
                                    </li>
                                {% endfor %}
                            </ul>
                            
                            <a href="{% url 'order_list_view' %}" class="btn btn-custom">Вернуться к списку заказов</a>
                            <a href="{% url 'order_update_view' order.pk %}" class="btn btn-custom">Редактировать</a>
                            <a href="{% url 'order_delete_view' order.pk %}" class="btn btn-custom">Удалить</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}

shopproject/shop/templates/order/order_form.html
{% extends "base.html" %}
{% load static %}

{% block title_name %}
Guiznotes - {% if form.instance.pk %}Редактировать заказ{% else %}Добавить новый заказ{% endif %}{% endblock %}
{% block content %}
{% if user.is_authenticated and user.is_staff %}
   <div class="container contact-container">
            <div class="row justify-content-center">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <h2>{% if form.instance.pk %}Редактировать заказ{% else %}Добавить новый заказ{% endif %}</h2>
                            <form method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                {{ form.as_p }}
                                <button type="submit" class="btn btn-custom">Сохранить</button>
                            </form>
                            <a href="{% url 'order_list_view' %}" class="btn btn-custom mt-3">Вернуться к списку заказов</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
{% else %}
            <br>
            <h1 class="text-center">Сначала войдите в аккаунт администратора</h1>
   {% endif %}

{% endblock %}

shopproject/shop/templates/order/order_list.html
{% extends 'base.html' %}
{% load static %}

{% block title_name %}Guiznotes - Список заказов{% endblock %}

{% block link_style %}
    {{ block.super }} 
{% endblock %}

{% block content %}
{% if user.is_authenticated and user.is_staff %}
   <div class="container contact-container">
            <div class="row justify-content-center">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <h2>Заказы</h2>
                            <a href="{% url 'order_create_view' %}" class="btn btn-custom mb-3">Добавить новую позицию</a>
                            <ul class="list-font">
                                {% for position in orders %}
                                    <li>
                                        <a href="{% url 'order_detail_view' position.pk %}">Заказ №{{ position.pk }}</a>
                                        <a href="{% url 'order_update_view' position.pk %}">Редактировать</a>
                                        <a href="{% url 'order_delete_view' position.pk %}">Удалить</a>
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
{% else %}
            <br>
            <h1 class="text-center">Сначала войдите в аккаунт администратора</h1>
   {% endif %}

{% endblock %}